apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secret-cert-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "secret-cert-controller.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "secret-cert-controller.name" . }}
    spec:
      serviceAccountName: {{ include "secret-cert-controller.fullname" . }}

      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}

      containers:
      - name: controller
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        env:
        - name: CERT_SERVER
          value: "{{ .Values.controller.certServer }}"
        - name: HTTP_TIMEOUT
          value: "{{ .Values.controller.httpTimeout }}"
        - name: CONFIG_PATH
          value: "{{ .Values.controller.configSync.mountPath }}/config.yaml"
        - name: SYNC_INTERVAL
          value: "{{ .Values.controller.configSync.syncInterval }}"
          {{- if .Values.controller.httpProxyUrl }}
        - name: HTTPPROXY_URL
          value: "{{ .Values.controller.httpProxyUrl }}"
          {{- end }}

        volumeMounts:
        - name: config
          mountPath: {{ .Values.controller.configSync.mountPath }}
          readOnly: true

        resources:
{{ toYaml .Values.resources | indent 10 }}

      volumes:
      - name: config
        configMap:
          name: {{ .Values.controller.configSync.existingConfigMap | default (printf "%s-config" (include "secret-cert-controller.fullname" .)) }}
